services:
  - type: web
    name: telegram-downloader-bot
    env: docker
    repo: OtabekIlhomov/yt-insta-bot  # 👉 замени на свой GitHub репозиторий
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: COOKIES_PATH
        value: /app/cookies.txt  # путь внутри контейнера (если используешь)

